# Quarkus configuration
quarkus.application.name=enterprise_entropy
quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.datasource.dev-ui.enabled=true
quarkus.analytics.disabled=false
quarkus.swagger-ui.enabled=true
quarkus.datasource.key.jdbc.enable-metrics=true

# DataSource Configuration
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=drools
quarkus.datasource.password=drools
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/enterprise_entropy
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.default-schema=rules
quarkus.hibernate-orm.key.database.generation=none




