# Quarkus configuration
quarkus.application.name=quarkus_service
quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.datasource.dev-ui.enabled=true
quarkus.analytics.disabled=false
quarkus.swagger-ui.enabled=true
quarkus.datasource.key.jdbc.enable-metrics=true

# DataSource Configuration
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url= ${DB_URL}
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.default-schema=${DB_SCHEMA}
quarkus.hibernate-orm.key.database.generation=none




