package org.acme.features.domain;

public enum Event {
    AUDIT_DISCOVERS,
    CLARIFY_SOMEHOW,
    CUSTOMER_COMPLAINS,
    DECLARE_ENTROPY_ABANDONED,
    DECLARE_ENTROPY_COMPLETE,
    DECLARE_ENTROPY_REDUCTION,
    DISCOVER_DISAGREEMENT,
    EXECUTIVE_REMEMBERS,
    FORGET_FOR_LONG_TIME,
    POSTPONE,
    REALIZE_WRONG_DIRECTION,
    REJECT_FUNDAMENTALLY,
    REWORK,
    SEND_TO_QA,
    START_ANYWAY,
    THIS_IS_ALL_WRONG,
}
