package org.acme.features.domain;

public enum State {
    IDEA_FOG,
    PRETEND_PLANNING,
    HEROIC_IMPLEMENTATION,
    PHILOSOPHICAL_DEBATE,
    STRESS_THE_THING,
    TEMPORARILY_POSTPONED,
    ZOMBIE_FEATURE,
    ENTROPY_REDUCTION,
    ENTROPY_COMPLETE,
    ENTROPY_ABANDONED
}
